config/routes.rb
OscollectShare::Application.routes.draw do
  resources :sessions
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"

  resources :password_resets

  resources :users

  resources :shares
  get "shares_list" => "shares#list", :as => "shares_list"

  resources :api_keys

  root :to => "api_keys#index"
end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%# .btn-navbar is used as the toggle for collapsed navbar content ...
           the following works on most mobile devices or when the user shrinks their browser window: %>
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%# everything you want hidden at 940px or less, place within here: %>
      <div class="container nav-collapse">
        <ul class="nav">
		      <li><a class="brand" href="/">osCollect Sharing&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></li>
					<li class="dropdown">
					  <a href="#" class="dropdown-toggle" data-toggle="dropdown">API Keys<b class="caret"></b></a>
					  <ul class="dropdown-menu">
					    <li><%= link_to 'List', api_keys_path %></li>
					    <li><%= link_to 'Generate New', new_api_key_path %></li>
					  </ul>
					</li>
					<li><%= link_to 'Shares', shares_list_path %></li>
					<li class="dropdown">
					  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admins<b class="caret"></b></a>
					  <ul class="dropdown-menu">
					    <li><%= link_to 'List', users_path %></li>
					    <li><%= link_to 'New', new_user_path %></li>
					  </ul>
					</li>
        </ul>
        <%= render partial: 'layouts/right_side_menu' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_right_side_menu.html.erb
<ul class="nav pull-right" style="margin-right:-50px">
  <li><%= link_to 'Profile', edit_user_path(current_user), 'data-method'=>"get" %></li>
  <li><%= link_to 'Logout', logout_path, 'data-method'=>"get" %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>osCollect Sharing</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<%= render partial: 'layouts/navbar' %>
<div class="container">
  <div class="content">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <%= msg  %>
      </div>
    <% end %>
    <div class="row">
      <div class="span12">
        <%= yield %>
      </div>
    </div><!--/row-->
  </div><!--/content-->
  <footer style="text-align:center">
    <hr />
    <p>2013 osCollect Sharing&nbsp;&nbsp;&nbsp;&nbsp;<%= "#{Time.now.utc.strftime("%A, %b %-d, %Y %H:%M:%S %Z")}" %></p>
  </footer>
</div><!-- /container -->
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>osCollect Sharing</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <style type="text/css">
    html, body {
      background-color: #eee;
    }
    body {
      padding-top: 40px;
    }
    .container {
      width: 300px;
    }
    .container > .content {
      background-color: #fff;
      padding: 20px;
      margin: 0 -20px;
      -webkit-border-radius: 10px 10px 10px 10px;
         -moz-border-radius: 10px 10px 10px 10px;
              border-radius: 10px 10px 10px 10px;
      -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);
         -moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);
              box-shadow: 0 1px 2px rgba(0,0,0,.15);
    }
    .login-form {
      margin-left: 65px;
    }
    legend {
      margin-right: -50px;
      font-weight: bold;
      color: #404040;
    }
  </style>
</head>
<body class="logged_out new">
<div class="login_wrapper">
  <%= yield %>
  <div class="clear"></div>
</div>
</body>
</html>